fix(hopeful): retry the yanrn cover command 3 times

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,7 +28,28 @@ jobs:
       - name: Build
         run: yarn build
       - name: Test
-        run: yarn cover
+        run: |
+          function retry() {
+            local n=0
+            local try=$1
+            local cmd="${@:2}"
+            [[ $# -le 1 ]] && {
+              echo "Usage $0 <retry_number> <Command>"
+            }
+          
+            until [[ $n -ge $try ]]; do
+              $cmd && break || {
+                echo "Command Fail.."
+                # echo the n++ else the ((n++)) *seems* to be treated as an exit code
+                # and -u will bail
+                echo $((n++))
+                echo "retry $n ::"
+                sleep 1
+              }
+          
+            done
+          }
+          retry 3 yarn cover
         env:
           CI: true
       - name: Report coverage
